# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Social Networking and Professional Development' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Social Networking and Professional Development

pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Storage'
pod 'Firebase/Firestore'
pod 'Firebase/Database'
pod 'SDWebImage', '~> 4.0'
pod 'JSQMessagesViewController'
pod 'IQKeyboardManager'

end
